# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py

# Set the version of Python to 3.10 and use pyproject.toml for dependencies
python:
  install:
    - method: pip
      path: .

# Optionally configure Read the Docs for additional formats
formats:
  - pdf
  - epub

# Optionally set up additional build commands
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.11"
  commands:
    - pip install .[docs]
    - make html
